Econify/ad.js

buildspec.yml
Once i test the publish command in npm with auto tagging i will uncomment the publish in the buildspec.yml and the pipeline will be set.
=> buildspec and fix for pr buildspec

buildspec.yml, package.json
Encrypted NPM token
* New KMS key added to AWS
* IAM permissions locked down to just this one policy -- only this codebuild can call "Decrypt" on this secret
=> release 2.0.0-beta.5

src/Ad.ts, tests/plugins/GenericPlugin.test.ts, tests/utils/insertElement.test.ts
Almost up to 80% across the board.
=> insertElement & genericPlugin tests

src/Ad.ts, src/networks/DFP.ts, src/plugins/Debug.ts, src/types.ts
I added comments in this pr, please read them and weigh in if you have a strong opinion.
=> Metadata in debug mode

docs/error.md, package.json, rollup-plugins/production-pruning.js, rollup.config.js, src/Ad.ts, src/networks/DFP.ts
This fixes a few bugs introduced via a rebase and reduces the bundle size to 5kb
=> [SB] Fix bugs in DFP implementation and minify bundle to 5kb

docs/README.md, docs/default-network.md, docs/dfp-network.md, docs/lazy-load-plugin.md, docs/refresh-plugin.md, docs/responsive-plugin.md
No more updating urls in documentation for unpkg links
=> Change unpkg from versions to latest tag

docs/README.md, docs/default-network.md, docs/dfp-network.md, docs/lazy-load-plugin.md, docs/refresh-plugin.md, docs/responsive-plugin.md, package.json
Update links in documentation to match new unpkg bundle names
=> release 2.0.0-beta.6

rollup-plugins/production-pruning.js
- Removed all dispatchEvent lines from production build
- [ x] Yes
- [x ] N.A.
- [ x] N.A.
- [ x] No
=> remove dispatchEvent in production

docs/error.md, rollup-plugins/production-pruning.js
- Noticed that the errors were repeating themselves in the documentation so I put together a quick fix.
- [x ] Yes
- [ x] Yes
- [x ] Yes
- [ x] No
=> Errors fix

docs/error.md, docs/sticky-plugin.md, package-lock.json, package.json, src/plugins/Sticky.ts, src/utils/stickybits.js
- Remove stickybits dependency
- Add docs for sticky ads
- [x ] Yes
- [x ] Yes
- [x ] N.A.
- [x ] No
=> change docs, remove plugin

package.json
Release beta.7
Remove all dependencies
=> Release V2.0.0-beta.7

package.json
* Sizes.json in unpkg
* remove rollup cli
* bugfixes
=> release 2.0.0-beta.8

docs/error.md, docs/lazy-load-plugin.md, docs/sticky-plugin.md, src/plugins/AutoRender.ts, src/plugins/Sticky.ts, src/types.ts, tests/plugins/Sticky.test.ts
Add sticky offset option to sticky plugin, change offset option in autoRender to renderOffset, add test and documentation
- [x ] Yes
- [x ] Yes
- [x ] Yes
- [x ] No
=> Sticky offset

package.json
* Offset for sticky and autoRender with backwards compat
=> Release v2.0.0-beta.10

package-lock.json, package.json, src/Ad.ts
=> [SB] Remove display inline-block

docs/error.md, package.json, src/networks/DFP.ts
Allow GPT to be preloaded and not re-request
- [X ] N.A.
- [X ] N.A.
- [X ] Yes
- [ X] Yes
=> [SB] Check for a preloaded DFP script

docs/error.md, package.json, src/Ad.ts, src/types.ts, tests/ad.test.js
Configurations at ad level were overriding all page default configurations inappropriately.
=> [MM] Ad configuration overrides

demo/index.html, docs/error.md, package.json, src/plugins/DeveloperTools.ts
=> Temp hotfix feature

docs/adtest.js
=> Include an adblock detection script

demo/index.html, docs/error.md, package.json, src/index.ts, src/plugins/AutoRender.ts, src/plugins/DeveloperTools.ts, src/plugins/GenericPlugin.ts, src/plugins/Sticky.ts, src/types.ts
This fixes developer tools, attaches AdJS to the window regardless of import type, and adds a config check fn on base plugin
=> [MM]: Developer tools upgrades

docs/error.md, package.json, src/plugins/GenericPlugin.ts
- if feature:
- if bugfix:
- [x ] Yes
- [x ] N.A.
- [x ] N.A.
- [x ] Yes
=> fix autorender bug

package.json, src/networks/DFP.ts
Load GPT from the same location that ads are coming from to reduce dns lookups
- [ X] N.A.
- [X ] N.A.
- [X ] Yes
- [X ] Yes
=> Updated gpt location

demo/index.html
- if feature:
- if bugfix:
- [x ] N.A.
- [x ] N.A.
- [ x] N.A.
- [x ] No
=> update copyright date

package-lock.json, package.json, src/networks/DFP.ts
Fixes 392 vulnerabilities found by `npm audit`. There still remains some low priority vulnerabilities, and 1 moderate vulnerability. 
N/A
=> [RK] Fix 392 vulnerabilities detected by npm

package-lock.json, package.json
Use `npm audit fix` to resolve 4709 vulnerabilities reported by npm
=> [RK] Fix 4709 vulnerabilities
